apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
      - image: ${project.artifactId}:${project.version}
        name: ${project.artifactId}
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTIONS
          value: "-Dspring.profiles.active=openshift"