- name: Docker image release
  hosts: localhost
  become: false
  gather_facts: no
  vars:
    registry: "{{ docker_registry }}" 
    user: "{{ docker_user }}"
    password: "{{ docker_password }}" 
    image: "{{ docker_image }}" 
    tag: "{{ docker_tag }}"
    path: "{{ dockerfile }}" 
    githttpprotocol: "{{ githttpprotocol }}"
    gituser: "{{ gituser }}" 
    gitpassword: "{{ gitpassword }}" 
    gitrepo: "{{ gitrepo }}" 
    gitrepodestinationpath: "{{ gitrepodestinationpath }}"
  tasks:

    - name: Get updated files from git repository 
      git: 
        repo: "{{ githttpprotocol }}://{{ gituser }}:{{ gitpassword }}@{{ gitrepo }}"
        dest: "{{ gitrepodestinationpath }}"

    - name: Log into private registry and force re-authorization
      docker_login:
         registry: "{{ registry }}"
         username: "{{ docker_user }}" 
         password: "{{ docker_password }}"
         reauthorize: yes

    - name: Build an image and push it to a private repo
      docker_image:
         path: "{{ dockerfile}}"
         name: "{{ registry }}/{{ image }}"
         tag: "{{ tag }}"
         push: yes





